name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install

      - name: Clean old Mochawesome reports
        run: rm -rf cypress/reports 

      - name: Run Cypress Tests
        run: npm run cy:run

      - name: Generate Mochawesome Report
        run: npx mochawesome-merge cypress/reports/*.json > mochawesome.json && npx mochawesome-report-generator mochawesome.json  

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
   
      